Vagrant.configure("2") do |config|
    config.vm.box      = "debian/stretch64"
    config.vm.hostname = "sheetstorm"

    config.vm.network "private_network", ip: "172.30.2.3"

    config.vm.provider :virtualbox do |virtualbox|
        virtualbox.memory = 2048
        virtualbox.gui    = false
    end

    extra_vars = {}
    extra_vars['sheetstorm_version'] = ENV['SHEETSTORM_VERSION'] if ENV.key?('SHEETSTORM_VERSION')
    config.vm.provision "ansible" do |ansible|
        ansible.compatibility_mode = "2.0"
        ansible.playbook           = "configure-sheetstorm-vm.yml"
        ansible.extra_vars         = extra_vars
        ansible.inventory_path     = "./inventory"
        ansible.limit              = "all"
    end
end
