# Generated by Django 2.1.8 on 2019-05-27 11:53

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[users.validators.UserAgeValidator(18, 99)], verbose_name='date of birth'),
        ),
    ]
