# Generated by Django 2.2.2 on 2019-07-01 06:53

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190614_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'blank': 'Please enter correct email address'}, max_length=255, unique=True, validators=[users.validators.UserEmailValidation()], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(error_messages={'null': 'Please enter your password'}, max_length=128),
        ),
    ]
