# Generated by Django 2.1.1 on 2019-03-22 13:21

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import employees.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20190313_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='work_hours',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='This value must be greater than 0.'), django.core.validators.MaxValueValidator(Decimal('24.00'), message='This value cannot be greater than 24:00.'), employees.common.validators.MaxDecimalValueValidator(Decimal('0.59'))]),
        ),
    ]
