# Generated by Django 2.1.1 on 2019-04-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20190412_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='task_activities',
            field=models.CharField(choices=[('PROJECT_MANAGEMENT', 'Project Management'), ('MEETING', 'Meeting'), ('SPEC_AND_DOCS', 'Spec & Docs'), ('DESING_AND_RESEARCH', 'Design & Research'), ('FRONTED_DEVELOPMENT', 'Frontend Development'), ('BACKEND_DEVELOPMENT', 'Backend Development'), ('QUALITY_ASSURANCE_TESTING', 'Quality Assurance / Testing'), ('TRAVEL', 'Travel'), ('DEVOPS', 'DevOps'), ('REVIEW', 'Review'), ('CONFERENCE', 'Conference'), ('OTHER', 'Other'), ('ADMINISTRATIVE', 'Administrative'), ('MARKETING', 'Marketing'), ('TRAINING', 'Training'), ('MENTORSHIP', 'Mentorship'), ('GRAPHIC_DESIGN', 'Graphic design')], default='OTHER', max_length=20),
        ),
    ]
