# Generated by Django 2.1.1 on 2019-04-23 20:20

from django.db import migrations, models
import django.db.models.deletion

def add_default_task_activity(apps, _schema_editor):
    TaskActivityType = apps.get_model('employees', 'TaskActivityType')

    default_activity_type = TaskActivityType(name='Other')
    default_activity_type.full_clean()
    default_activity_type.save()


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20190412_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Other', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='task_activities',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='employees.TaskActivityType'),
        ),
        migrations.RunPython(
            add_default_task_activity,
            reverse_code=migrations.RunPython.noop,
        )
    ]
