# Generated by Django 2.1.1 on 2019-05-12 23:54

from django.db import migrations, models
import django.db.models.deletion
import employees.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20190507_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='task_activities',
            field=models.ForeignKey(default=employees.models.TaskActivityType.get_or_create_default_task_activity_type_pk, on_delete=django.db.models.deletion.SET_DEFAULT, to='employees.TaskActivityType'),
        ),
    ]
