# Generated by Django 2.2.2 on 2019-07-25 08:50

from django.db import migrations
from markdown import markdown
from markdown_checklists.extension import ChecklistsExtension

from employees.common.exports import convert_markdown_html_to_text


def remove_markdown(apps, schema_editor):
    Report = apps.get_model("employees", "Report")

    for report in Report.objects.all():
        new_description = convert_markdown_html_to_text(
            markdown(
                report.description,
                extensions=["extra", "sane_lists", "wikilinks", "nl2br", "legacy_em", ChecklistsExtension()],
            )
        )
        report.description = new_description
        report.save()


class Migration(migrations.Migration):

    dependencies = [("employees", "0005_auto_20190530_1211")]

    operations = [migrations.RunPython(remove_markdown)]
