# Generated by Django 2.2.2 on 2019-07-25 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("employees", "0005_auto_20190530_1211")]

    operations = [
    ]
