# Generated by Django 2.1.8 on 2019-05-27 15:05

from datetime import timedelta
from django.db import migrations, models


def migrate_decimal_work_hours_field_to_duration_field(apps, _schema_editor):
    Report = apps.get_model("employees", "Report")

    for report in Report.objects.all():
        (hours, minutes) = report.work_hours.to_eng_string().split(".")
        timedelted_work_hours = timedelta(hours=int(hours), minutes=int(minutes))
        report.converted_work_hours = timedelted_work_hours
        report.full_clean()
        report.save()


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20190512_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='converted_work_hours',
            field=models.DurationField(default=timedelta(minutes=0)),
            preserve_default=False,
        ),
        migrations.RunPython(
            migrate_decimal_work_hours_field_to_duration_field,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='report',
            name='work_hours',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='converted_work_hours',
            new_name='work_hours',
        )
    ]
