# Generated by Django 2.2.3 on 2019-07-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('start_date', models.DateField(help_text='Please enter date in this format: YYYY-MM-DD')),
                ('stop_date', models.DateField(blank=True, null=True)),
                ('suspended', models.BooleanField(default=False)),
            ],
        ),
    ]
