# Generated by Django 2.2.3 on 2019-07-30 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='managers',
            field=models.ManyToManyField(related_name='manager_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
