# Generated by Django 2.2.3 on 2019-08-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0002_auto_20190730_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_notification_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
