# Generated by Django 2.1.1 on 2019-05-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0002_auto_20190412_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(help_text='Please enter date in this format: YYYY-MM-DD'),
        ),
    ]
