# Generated by Django 2.2.3 on 2019-07-22 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0004_auto_20190709_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='terminated',
            new_name='suspended',
        ),
    ]
