from .development import *

ENVIRONMENT = 'testing'

INSTALLED_APPS.append('behave_django')

HEADLESS_BROWSER_RUN = False

CSRF_COOKIE_SECURE = False

SESSION_COOKIE_SECURE = False

DEFAULT_ITERATIONS_FOR_FAILED_INTERACTION = 10

DEFAULT_TIMEOUT_FOR_FAILED_INTERACTION = 1
