- become:      yes
  become_user: sheetstorm
  block:
    - name: Check if sheetstorm repository exist
      stat:
        path:   ~/sheetstorm
      register: result

    - fail: msg="The sheetstorm repository must exist before you can migrate database."
      when: not result.stat.exists

    - name:   Migrate database
      django_manage:
          command:    migrate
          app_path:   "{{ sheetstorm_dir }}"
          virtualenv: "~/virtualenv"
