- become:      yes
  become_user: sheetstorm
  block:
    - name: Check if sheetstorm repository exist
      stat:
        path:   ~/sheetstorm
      register: result

    - fail: msg="The sheetstorm repository must exist before the secret file can be uploaded"
      when: not result.stat.exists

    - name:  Create secrets directory
      file:
        path:  "{{ sheetstorm_dir }}/sheetstorm/settings/secrets/"
        state: directory

- become:      yes
  become_user: root
  block:
    - name:   Upload secret file
      copy:
        src:    "{{ sheetstorm_secret_dir }}/secrets.py.vault"
        dest:   "{{ sheetstorm_dir }}/sheetstorm/settings/secrets/secrets.py"
        mode:   0644
        owner:  sheetstorm
        group:  sheetstorm
